[package]
name = "terminal_alpha_beta"
version = "0.3.1"
authors = ["zireael9797 <ryanhossain9797@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = {version = "0.2.21", features = ["full"]}
telegram-bot = {git = "https://github.com/telegram-rs/telegram-bot"}
dotenv = "0.15.0"
lazy_static = "1.4.0"
once_cell = "1.4.0"
colored = "1.9.3"
base64 = "0.12.2"
regex = "1"
rand = "0.7"
reqwest = "0.10.6"
scraper = "0.12.0"
select = "0.4.3"
openssl = { version = "0.10", features = ["vendored"] }
openssl-probe = "0.1.2"
closestmatch = "0.1.2"
mongodb = "1.0.0"
serde = "1.0.113"
async-trait = "0.1.36"
serde_json = "1.0"
snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" }
serenity = { git = "https://github.com/Lakelezz/serenity", branch = "await", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils", "cache"]}

[dev-dependencies]
assert_cmd = "1"
predicates = "1"