[package]
name = "terminal_alpha_beta"
version = "0.3.1"
authors = ["zireael9797 <ryanhossain9797@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = {version = "0.2.21", features = ["full"]}
telegram-bot = {git = "https://github.com/telegram-rs/telegram-bot"}
dotenv = "0.15.0"
once_cell = "1.4.0"
colored = "1.9.3"
regex = "1"
rand = "0.7"
reqwest = {version = "0.10.6", features = ["blocking"]}
openssl = { version = "0.10", features = ["vendored"] }
openssl-probe = "0.1.2"
closestmatch = "0.1.2"
mongodb = "1.0"
serde = "1.0.114"
async-trait = "0.1.36"
serde_json = "1.0"
snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" }
serenity = { git = "https://github.com/Lakelezz/serenity", branch = "await", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils", "cache"]}
search_with_google = { version = "0.3.1", git = "https://gitlab.com/zireael9797/search-with-google", branch = "master" }