[package]
name = "terminal_alpha_beta_rust"
version = "0.1.0"
authors = ["zireael9797 <ryanhossain9797@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
tokio = {version = "0.2.16", features = ["full"]}
telegram-bot = "0.7"
dotenv = "0.15.0"
regex = "1"