[package]
name = "terminal_alpha_beta_rust"
version = "0.1.0"
authors = ["zireael9797 <ryanhossain9797@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = {version = "0.2.20", features = ["full"]}
telegram-bot = "0.7"
dotenv = "0.15.0"
lazy_static = "1.4.0"
base64 = "0.12.1"
regex = "1"
reqwest = "0.10.4"
scraper = "0.12.0"
select = "0.4.3"
openssl = { version = "0.10", features = ["vendored"] }
openssl-probe = "0.1.2"
closestmatch = "0.1.2"
serde = "1.0.110"
serde_json = "1.0"
snips-nlu-lib = { git = "https://github.com/snipsco/snips-nlu-rs", branch = "master" }
